apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: poc-auteur
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "auteur"
  MYSQL_DATABASE: "auteur"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "auteur"
